name: Build and Publish
on: push

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    timeout-minutes: 600

    steps:
    - uses: actions/checkout@v1

    - name: Build Image
      run: |
        docker image build . -t protonvpn-docker
