name: Build and Publish
on: push

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    timeout-minutes: 600

    steps:
    - uses: actions/checkout@v1

    - name: Build Image
      run: |
        docker image build . -t protonvpn-docker

    - name: Publish Image
      run: |
        docker login docker.pkg.github.com -u c01o -p ${{ secrets.GH_PAT }}
        docker tag protonvpn-docker docker.pkg.github.com/c01o/protonvpn-docker/protonvpn-docker:latest
        docker push docker.pkg.github.com/c01o/protonvpn-docker/protonvpn-docker:latest

